### ISSUE TITLE
Post issues

### ISSUE THREAD

**Issue by huangyuzhang** [huangyuzhang/Fizzy-Theme#1]
1. The content headings size `h2` and `h3` are larger than the post title itself on **mobile devices**;
2. Better **blockquote** style: color, italic font;
3. Author block will be blank with a box border when author avatar is unset.

**Comment by rafuru** [comment]
I can add a weird style when you post code with markup block

**Comment by huangyuzhang** [comment]
> I can add a weird style when you post code with markup block

I am not 100% sure what weird style you've got, can you explain it a bit more or upload an screenshot of that? Cheers!

**Comment by huangyuzhang** [comment]
Resolved in v0.1.0
