### ISSUE TITLE
Collection support

### ISSUE THREAD

**Issue by huangyuzhang** [huangyuzhang/Fizzy-Theme#14]
ref:
- [https://docs.ghost.org/tutorials/creating-content-collections/](https://docs.ghost.org/tutorials/creating-content-collections/)
- [https://docs.ghost.org/tutorials/chronological-posts/](https://docs.ghost.org/tutorials/chronological-posts/)

**Comment by duncanjbain** [comment]
How are you planning on implementing this? From reading the URLs it looks like you have to manually edit the routes.yml file and add your specific URLs and tags you want to filter posts on, so it looks quite site specific to me?

I might be wrong!

**Comment by huangyuzhang** [comment]
@duncanjbain Thanks for your comment. 

I haven't attempted to work on that yet. Thus my knowledge on that is still quite limited. But I think you are right according to the doc of Ghost. I assume that's a function mostly needed by big publications and/or companies rather than bloggers. That's also the reason I don't want to rush it.

That being said, please feel free to implement it as a separate branch and if that works a PR would always benefit us!

Cheers!

**Comment by duncanjbain** [comment]
@huangyuzang No worries! I was just looking to see if there was any issues I could to solve :)

I'll dig deeper and see if there is anything that could be implemented that's not site specific.

**Comment by huangyuzhang** [comment]
@duncanjbain Really appreciate that! You have no idea how this makes me excited about the future of this theme. ☺️

**Comment by duncanjbain** [comment]
It's a great theme! I'm not promising my contributions will be fantastic, I'm only just starting to learn programming, although I've dabbled since I was about 9 years old onwards. I'm now attempting a career change from mechanical engineering to software development. I'm planning on keeping a blog to track my progress, and this theme is perfect!

**Comment by huangyuzhang** [comment]
Finished in v1.0.7
