### ISSUE TITLE
Search system

### ISSUE THREAD

**Issue by handicrap** [huangyuzhang/Fizzy-Theme#18]
Really like this theme! My question is  would it be possible to integrate a search system into this theme?

**Comment by huangyuzhang** [comment]
@handicrap Thank you! 
Yes, a search system would be a nice-to-have. However, as you may notice that Ghost Admin already has a native search system for posts and pages. It might be a good idea to wait for Ghost team to make it available in the front-end. 

So far there are several third-party search solutions available, I need to test the functionality before integrating any of them.

- [ghost-search](https://github.com/HauntedThemes/ghost-search)
- [ghostHunter](https://github.com/jamalneufeld/ghostHunter)
- Algolia
- ElasticSearch

**Comment by huangyuzhang** [comment]
finished, will be available on v1.0.0

![image](https://user-images.githubusercontent.com/40261916/58662711-bdec0880-8322-11e9-93d7-dfcc01a024da.png)
