### ISSUE TITLE
How to customize my home page?

### ISSUE THREAD

**Issue by AlienKevin** [huangyuzhang/Fizzy-Theme#21]
Hi, I'm a new user of Ghost and Fizzy. Thanks for the fantastic work! Even though the theme looks gorgeous, my home page looks very blank. I want to add a title and more contents to my home page. How can I do that?

**Comment by huangyuzhang** [comment]
@AlienKevin Glad to know you like this theme!
There are a few things you can do to populate your homepage, such as the top **showcase**, please read the README.md for more information. Also if you want, you can post your site's URL so I'd be able to give it a look to see what might be improved.

**Comment by AlienKevin** [comment]
Thanks, I will check out the showcase, It looks promising.

**Comment by AlienKevin** [comment]
I managed to add a whole-page title on my website and I think my problem is solved. I would also be happy to receive any suggestions for improvement, here's my URL: http://electrifiedlearning.org/
