### ISSUE TITLE
主题很好，开个issue鼓励下作者

### ISSUE THREAD

**Issue by Smith-Cruise** [huangyuzhang/Fizzy-Theme#29]
看到开 issue 的都是英文，我就中文 issue 代表国人鼓励下，希望作者能保持更新，不要半路停更了。🤗🤗🤗🤗
这个主题刚好满足了我所有的需求，尤其是 latex 哈。

**Comment by huangyuzhang** [comment]
感谢使用和给star支持！

简单看了一下你的站，建议你使用最新的开发版本 v1.0.17，直接下载zip上传就可以使用了。比v1.0.0有完善不少，具体可以参考CHANGELOG。只不过最近比较忙就只有修修bug还没来得及发一个新的release。

**Comment by Smith-Cruise** [comment]
我一开始装 v1.0 版本是发现了不少 bug，然后就用了你的开发版，bug也没了。给你点个赞👍。
