### ISSUE TITLE
字体文件里面使用了googlefont，导致网站打开极慢

### ISSUE THREAD

**Issue by Smith-Cruise** [huangyuzhang/Fizzy-Theme#30]
我看到了主题里面字体用了googlefont，要知道google在天朝是有点问题的。最好能提供一个开关能切换字体cdn。我自己现在已经改成了阿里字体的cdn，可以给作者参考下：https://www.iconfont.cn/webfont?spm=a313x.7781069.1998910419.12&puhui=1#!/webfont/index

**Comment by Smith-Cruise** [comment]
![image](https://user-images.githubusercontent.com/18729228/63567674-1b4fc880-c5a5-11e9-8a79-dc5f2361d5b4.png)
还有一个浏览器一直报这个错误，popup里面的，不知道什么原因。

**Comment by huangyuzhang** [comment]
> 我看到了主题里面字体用了googlefont，要知道google在天朝是有点问题的。最好能提供一个开关能切换字体cdn。我自己现在已经改成了阿里字体的cdn，可以给作者参考下：https://www.iconfont.cn/webfont?spm=a313x.7781069.1998910419.12&puhui=1#!/webfont/index

嗯，这个会考虑。不过我现在（伦敦）测试打开你的站速度变得非常慢，甚至css都无法正确加载。所以可能cdn这个问题还是要留给使用的朋友自己决定。

汽水主题主要引用googlefont是用于英文字体，另外这个主题已经对中文字体做了优化，所以国内的朋友如果是全中文内容的话直接在 `default.hbs` 去掉或注释 `<link href="https://fonts.googleapis.com/css?family=Montserrat:400,600,700" rel="stylesheet">`即可。

另外之后有可能把核心的css和js放到本地调用；或者另外开一个分支来为国内的朋友做一下优化。

感谢建议！

> ![image](https://user-images.githubusercontent.com/18729228/63567674-1b4fc880-c5a5-11e9-8a79-dc5f2361d5b4.png)
> 还有一个浏览器一直报这个错误，popup里面的，不知道什么原因。

这个是1.0之前的一个遗留bug，因为是本地加载，又不影响使用，暂时没有去修复。之后有空了会修复。

**Comment by Smith-Cruise** [comment]
是的，我把你的全部链接换成了国内CDN，国内打开秒开了。

**Comment by huangyuzhang** [comment]
> 是的，我把你的全部链接换成了国内CDN，国内打开秒开了。

方便问一下国内一般都用那些CDN吗？😃

**Comment by Smith-Cruise** [comment]
jsdelivr (有国内 cdn 节点，但是速度没有国内本土做的好)
http://www.staticfile.org  (七牛的)
https://www.bootcdn.cn/ (个人偏好这个，js 库多，也快，之前我改动用的就是它)

**Comment by huangyuzhang** [comment]
> jsdelivr (有国内 cdn 节点，但是速度没有国内本土做的好)
> http://www.staticfile.org (七牛的)
> https://www.bootcdn.cn/ (个人偏好这个，js 库多，也快，之前我改动用的就是它)

感谢！
