### ISSUE TITLE
正文不显示

### ISSUE THREAD

**Issue by linzhangxing** [huangyuzhang/Fizzy-Theme#31]
换上1.1.1版本以后，博客正文不显示
<img width="881" alt="屏幕快照 2019-09-06 下午2 20 59" src="https://user-images.githubusercontent.com/5426042/64405398-90e18b80-d0b1-11e9-8c3e-3a225f380f74.png">

**Comment by huangyuzhang** [comment]
你好，我这边刚升级到了最新的Ghost 2.30.2 测试没有问题。无法复现你的问题，如果可能的话请提供多一点的信息，或者尝试其他版本是否没有问题，比如上一个版本 Fizzy Theme v1.0.17。

另外，你看一下你的 Ghost 版本是不是最新的吧。参考他们在2.30.2修复了一个类似的问题：
- https://gist.github.com/kevinansfield/8f64a592d820e3af1c297ccd4e7567e6
- https://github.com/TryGhost/Ghost-Admin/commit/e32110c73

**Comment by linzhangxing** [comment]
似乎是我的问题，我发现切换到官方主题依然会有同样的问题，我重新安装试试。
