### ISSUE TITLE
Search button reappears if you click it

### ISSUE THREAD

**Issue by peter-bloomfield** [huangyuzhang/Fizzy-Theme#37]
I've had a small problem with the search box reappearing after I disabled it.

**Steps to reproduce**
1. Ensure search button is hidden (show_search = false).
2. Open blog page in browser.
3. Click the area where the search button would appear if it was not hidden.

**Expected behaviour**
The search button should stay hidden. It should not respond to any clicks.

**Actual behaviour**
The search button appears when the area is clicked.

**Comment by huangyuzhang** [comment]
Thank you for posting this. It will be fixed in next release.

**Comment by huangyuzhang** [comment]
fixed in v1.3.1
