### ISSUE TITLE
Showcase isn't available on my homepage.

### ISSUE THREAD

**Issue by jwawon** [huangyuzhang/Fizzy-Theme#42]
Hi, 
First of all, thank you for this fantastic theme. This is what I have been looking for.

I wanted to apply your theme to my homepage.
But when I followed your direction (added the internal tag and added the code into Ghost site header), I wasn't able to active showcase, even tag archive, and post archive. 
In the showcase section, there is a message "console.error("The {{#get}} helper requires your theme to have API access.~"
Here is my homepage: https://jwawon.me

Are they additional directions that I should follow to enable showcase and custom templates?

**Comment by huangyuzhang** [comment]
Please try to update your Ghost to V3

**Comment by jwawon** [comment]
Appreciate!
I update my Ghost to V3. It is completely working now.
