### ISSUE TITLE
Tocify not working

### ISSUE THREAD

**Issue by denvergeeks** [huangyuzhang/Fizzy-Theme#45]
v1.3.2 Tocify is not working when set to true in the header script.

I am running Ghost v3.1.1

**Comment by huangyuzhang** [comment]
please provide sufficient information related to the issue you are facing and the process to reproduce the issue.

**Comment by denvergeeks** [comment]
Thank you for the quick reply, and THANK YOU for this awesome theme!

I have a fresh install of Ghost v3.1.1 here: https://fizzy.ghost-o-matic.com

I downloaded and enable the Master branch

I inserted into the Code Injection site header
```
<script>
    var show_toc = true; // enable TOC (default: false)
</script>
```
The TOC does not appear on any page

So, I also enabled the Template "Post with TOC" on all of the posts

The TOC still never appears

**Comment by denvergeeks** [comment]
I got it working! Not sure what the problem was, but TOC is now working on your Fizzy demo page so I just made sure to match mine with yours. Thank you again, my friend!
