### ISSUE TITLE
Latest master install looks strange

### ISSUE THREAD

**Issue by planetahuevo** [huangyuzhang/Fizzy-Theme#51]
Hi, 
I just install the theme from Git and it looks "bad" using master.
Installing the latest 1.3.2 tag looks fine. 
I think some of the latest changes with divs do not work when it is a clean install.
Could be this one: 
https://github.com/huangyuzhang/Fizzy-Theme/commit/8f671fd1d4eee3af90a8b4dff4e08058da0e17ae
Sorry for not having more info. I will try to debug it a little more when I get some time.

**Comment by huangyuzhang** [comment]
Thank you for your comment, I have reverted the pull request.
