### ISSUE TITLE
Different theme style when compared to demo site

### ISSUE THREAD

**Issue by hexclann** [huangyuzhang/Fizzy-Theme#61]
Thanks for this awesome theme! I installed it on my ghost instance and the style is very different when compared to your blog. Only system font is available, the image inserted does not fit all the way to the edge of the card. 

![chrome_XGrDDB23N6](https://user-images.githubusercontent.com/59732888/110982484-90a10b00-838e-11eb-9069-202bfa402b96.png)

I'm also seeing 404 errors for bulma css

![chrome_ynbI5VR3tp](https://user-images.githubusercontent.com/59732888/110982204-44ee6180-838e-11eb-86a9-1f6b131b9ae6.png)

The text in mobile site is very small when compared to your blog

![chrome_iPM0nbp6wD](https://user-images.githubusercontent.com/59732888/110982553-a6aecb80-838e-11eb-9777-a3fe370220c8.png)

**Comment by denvergeeks** [comment]
I had to use the full URL to the font files in the font.css for my site using Fizzy... like this...

![fizzy-font-css](https://user-images.githubusercontent.com/322529/110983771-6a945000-8327-11eb-863e-daebc61ae8cc.jpg)

**Comment by huangyuzhang** [comment]
> I'm also seeing 404 errors for bulma css
> 
> ![chrome_ynbI5VR3tp](https://user-images.githubusercontent.com/59732888/110982204-44ee6180-838e-11eb-86a9-1f6b131b9ae6.png)

I'm seeing a `.map` at the very end of each asset file, I am assuming the relative file path is broken. You may want to check the actual file path as well as the asset files referencing in the template.

**Comment by hexclann** [comment]
Thanks for the information
