### ISSUE TITLE
Right Align Header Tags

### ISSUE THREAD

**Issue by drvaya** [huangyuzhang/Fizzy-Theme#62]
I dont see an option to right align the headers.

Any pointers on how this can be done ?

<img width="1436" alt="Screenshot 2021-03-16 at 6 51 23 PM" src="https://user-images.githubusercontent.com/7770908/111315827-c1cc5480-8688-11eb-9e10-3646dfc44a55.png">

**Comment by denvergeeks** [comment]
`.navbar-menu {
    margin-right: -40px;
}`

**Comment by drvaya** [comment]
Ofcourse this is always possible, I meant to ask if there is some control in the theme.
Thanks for your answer !!
