### ISSUE TITLE
Ghost4.0

### ISSUE THREAD

**Issue by xuyisheng** [huangyuzhang/Fizzy-Theme#67]
你好，目前有支持Ghost4.0的计划吗

**Comment by huangyuzhang** [comment]
你好，目前来说暂时没有支持Ghost4.0的计划，因为Ghost现在目前有点偏商业了，然后之前使用的时候他那个编辑器对中文也不太友好。

自己目前是弃用Ghost了，不过这个会看实际的需求。

如果希望更新的同学多的话我可以抽空更新一下。

当然也欢迎各位来继续维护这个项目。

**Comment by huangyuzhang** [comment]
你好，目前最新版本[v1.3.5](https://github.com/huangyuzhang/Fizzy-Theme/releases/tag/v1.3.5)已支持Ghost V5，如果感兴趣可以更新一下。
