### ISSUE TITLE
QUESTION: Is there any HTML Version of Fizzy-Theme

### ISSUE THREAD

**Issue by KonstantinosVazaios** [huangyuzhang/Fizzy-Theme#68]

**Comment by huangyuzhang** [comment]
For Fizzy-Theme, you can use [GUI](https://github.com/huangyuzhang/gui) to generate your static site.
For [Fizzy-Jam](https://github.com/huangyuzhang/Fizzy-Jam), it uses eleventy to generate static site under `_site` folder.

**Comment by KonstantinosVazaios** [comment]
.
