### ISSUE TITLE
Header not same as the Demo

### ISSUE THREAD

**Issue by AmreshSinha** [huangyuzhang/Fizzy-Theme#70]
Hey There! :wave: 
Your theme is awesome!
I have recently started with Ghost. I installed your theme.
Everything is fine except the header is not same as your blog site.

![image](https://user-images.githubusercontent.com/35039730/142636413-1a5a0bf0-728a-409c-95d8-e1cccab52a66.png)

whereas yours look like this:

![image](https://user-images.githubusercontent.com/35039730/142636473-f27ac2b9-0568-4b14-a8de-e4782d3e3e74.png)

Is there any code injection which is not documented in the README? or a bug?

**Comment by mztiq** [comment]
Same for me, I'd appreciate some information on that too since the header of the demo looks even better.
Love your theme btw!

**Comment by huangyuzhang** [comment]
Sorry for the late fix. You should be able to see the centered header in the latest commit.
