### ISSUE TITLE
关于topics的疑问

### ISSUE THREAD

**Issue by afeng616** [huangyuzhang/Fizzy-Theme#71]
大佬你好，我想呈现想你/tags页面一样的标签云效果，请问是如何实现的呢？

**Comment by huangyuzhang** [comment]
你好，可以参考重写的项目：[Fizzy-Jam](https://github.com/huangyuzhang/Fizzy-Jam)

**Comment by afeng616** [comment]
😅 不肝了，这个版本才刚整明白。等下次想换UI在折腾！谢谢大佬的主题。[我的博客](https://afeng.plus)
不能说毫不相干只能说一模一样。
