### ISSUE TITLE
Error when to activate themes

### ISSUE THREAD

**Issue by mrlongshen** [huangyuzhang/Fizzy-Theme#74]
Got this error want to use this themes. 
Maybe some updates ?
![2023-03-24_08-05](https://user-images.githubusercontent.com/5020778/227390827-3fe60d02-55f2-4f03-a934-918cc4d90652.png)

**Comment by huangyuzhang** [comment]
Glad to know you intend to use it for your site.

As for the error comes from the install notice, you can simple open the `default.hbs` file and search for all `{{@site.lang}}` and replaced with `{{@site.locale}}`.

Let me know if you encounter any other problem after fixing this.
