### ISSUE TITLE
Ghost 5

### ISSUE THREAD

**Issue by ekoyuliawan** [huangyuzhang/Fizzy-Theme#75]
Hello, Fizzy is the most beautiful theme I have ever seen, thank you for creating this theme. Please maintenance/update it to support to Ghost 5. Ghost is very fast than other CMS, people would choose Ghost rather than WP for blogging. Thank you.

**Comment by denvergeeks** [comment]
Here is a screenshot of errors arising on installation in recent Ghost Version: 5.40.1

![Screenshot 2023-05-15 220942](https://github.com/huangyuzhang/Fizzy-Theme/assets/322529/1bd7760f-603f-4cde-bd73-0ecf4db870e9)

**Comment by huangyuzhang** [comment]
Actually you are still able to activate the theme.
I have made modifications to support Ghost V5 on [v1.3.5](https://github.com/huangyuzhang/Fizzy-Theme/releases/tag/v1.3.5) so just use this.
