### ISSUE TITLE
Menu item and site logo

### ISSUE THREAD

**Issue by mrlongshen** [huangyuzhang/Fizzy-Theme#76]
May I know where to edit the menu item. I have delete my menu. But I think your menu item is stick. How to edit it. 

. 

Also the site logo.

![6ACD8FB3-D4AA-40E6-9DB0-89BCA133C3BF](https://user-images.githubusercontent.com/5020778/227953874-9457a0be-7785-4bea-bd5b-406317e8bba3.jpeg)

**Comment by mrlongshen** [comment]
I think its a bugs from 1.3.3
Currently im using 1.3.2 its working fine. Just the alignment only like below.

How to fix that ?

![2023-03-28_15-53](https://user-images.githubusercontent.com/5020778/228167295-178cc64d-9e8f-4500-bc3a-a814de4f56fb.png)

**Comment by radoman93** [comment]
It's not working here either. Did you find a solution?

**Comment by huangyuzhang** [comment]
Hi there, this issues has been solved by the latest [release v1.3.4](https://github.com/huangyuzhang/Fizzy-Theme/releases/tag/v1.3.4).
