### ISSUE TITLE
Request for dark mode/How to turn enable dark mode

### ISSUE THREAD

**Issue by sec-fortress** [huangyuzhang/Fizzy-Theme#82]
I will be glad if someone in the team can please tell me how to add a dark mode feature or make the theme dark by default, thanks xD.

**Comment by denvergeeks** [comment]
https://www.spectralwebservices.com/blog/adding-a-dark-mode-button-to-your-ghost-blog/

Best Regards,

Jen

**Comment by sec-fortress** [comment]
Thanks
